// Copy the design tokens (CSS custom properties) from prompture-hub's dashboard
// so the app and the dashboard stay visually identical.
//
//   npm run sync-tokens                      # expects ../prompture-hub next to this repo
//   HUB_STYLES=/path/to/styles.css npm run sync-tokens
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const source = process.env.HUB_STYLES ?? resolve(root, "../prompture-hub/frontend/src/styles.css");
const css = readFileSync(source, "utf8");

function block(selector) {
  const start = css.indexOf(`${selector} {`);
  if (start < 0) throw new Error(`${selector} block not found in ${source}`);
  const end = css.indexOf("\n}", start);
  return css.slice(start, end + 2);
}

const out = `/* Generated by scripts/sync-tokens.mjs from prompture-hub's dashboard styles.
   Edit the hub's styles.css and re-run \`npm run sync-tokens\`; don't edit here. */

${block(":root")}

${block('[data-theme="dark"]')}
`;
writeFileSync(resolve(root, "src/styles/tokens.css"), out);
console.log(`tokens.css updated from ${source}`);
